version: "2"
services:
    proxy:
        build: nginx # ссылка на Dockerfile
        container_name: todo_proxy
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available/default:/etc/nginx/conf.d/default.conf
            - /private/var/log/nginx:/var/log/nginx
        depends_on: # Запустится только после `web`
            - web
        ports:
            - 80:80
        network_mode: host
        
    web:
        build: pm2
        container_name: todo_web
        volumes:
            - ../api:/app
        ports:
            - 3000:3000
        depends_on:
            - db
        network_mode: host

    db:
        image: mongo:3.4.2 # Cсылка на docker-image на https://hub.docker.com/
        container_name: todo_db
        volumes:
            - "./mongo_data:/data/db"
        network_mode: host

networks:
    default:
        external:
            name: "host"